config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'media#index'
  resources :media do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :medium
end

app/models/medium.rb
class Medium < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }

  belongs_to :user
  has_many :comments
  geocoded_by :address
  after_validation :geocode

  validates :author, presence: true
  validates :genre, presence: true

  # def self.search(search)
  #   if search
  #     find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
  #   else
  #     find(:all)
  #   end
  # end
  def self.search(search)
  if search
    self.where("title like ?", "%#{search}%")
  else
    self.all
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :media
  has_many :comments       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @medium = Medium.find(params[:medium_id])
    @medium.comments.create(comment_params.merge(user: current_user))
    redirect_to medium_path(@medium)
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :rating)
  end

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def destroy
    @medium = Medium.find_by_id(params[:id])
    return render_not_found if @medium.blank?
    return render_not_found(:forbidden) if @medium.user != current_user   
    @medium.destroy
    redirect_to root_path
  end

  def update
    @medium = Medium.find_by_id(params[:id])
    return render_not_found if @medium.blank?
    return render_not_found(:forbidden) if @medium.user != current_user
    @medium.update_attributes(medium_params)

    if @medium.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end
  
  def new
    @medium =Medium.new
  end

  def index
    @media = Medium.all.search(params[:search]).paginate(:per_page => 5, :page => params[:page])
  end 

  def show
    @medium = Medium.find_by_id(params[:id])
    @comment = Comment.new
    return render_not_found if @medium.blank?
  end

  def edit
    @medium = Medium.find_by_id(params[:id])
    return render_not_found if @medium.blank?
    return render_not_found(:forbidden) if @medium.user != current_user
  end


  def create
    @medium = current_user.media.create(medium_params)
    if @medium.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
 

  private

  def medium_params
    params.require(:medium).permit(:genre, :publisher, :title, :author, :description)
  end

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <%= link_to 'Bookends', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">

          <li class="nav-item">
            <%= link_to new_medium_path, class: 'nav-brand' do %>
              <i class="fas fa-bookmark"></i> -->
            New Stuff
            <% end %>
          </li>
        </ul>

        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>  
    <% if current_user %>
      You're signed in as <%= current_user.email %>.
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>

</html>

app/views/media/edit.html.erb
<div class="booyah-box col-10 offset-1">  
  <%= simple_form_for @medium do |f| %>
    <%= f.input :genre, :collection => ['Fiction', 'Non-Fiction', 'Science Fiction', 'Fantasy', 'Self-Help'] %>
    <%= f.input :publisher %>
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.submit "Fixit!!", class: 'btn btn-primary' %>
  <% end %>
</div>  

app/views/media/index.html.erb
<!--   <%= form_tag media_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :title => nil %>
    </p>
  <% end %> -->
<% @media.each do |medium| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to medium.title, medium_path(medium) %></h1><br />
    <i><%= medium.author %></i><br />
    <i><%= medium.publisher %></i><br />
    <i><%= medium.genre %></i><br />
    <p><%= medium.description %></p><br />

    <% if medium.user.present? %>
      <small><%= medium.user.email %></small>
    <% end %>
    <% if medium.comments.present? %> 
      <div class="col-12">
        <blockquote>
          <b><%= medium.comments.last.rating %></b> -
            <%= medium.comments.last.description %>
          <small><%= medium.comments.last.user.email %></small>
        </blockquote>
      </div> 
    <% end %>  
  </div>
<% end %>

<%= will_paginate @media %>

app/views/media/new.html.erb
<div class="booyah-box col-10 offset-1">
<h1>Put your stuff here</h1>
<%= simple_form_for @medium do |f| %>
  <%= f.input :genre, :collection => ['Fiction', 'Non-Fiction', 'Science Fiction', 'Fantasy', 'Self-Help'] %>
  <%= f.input :publisher %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :description %>
  <%= f.input :address %>
  <br />
  <%= f.submit 'Bookit!!', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/media/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @medium.title %></h1>
  <i><%= @medium.author %></i><br />
  <i><%= @medium.publisher %></i><br />
  <i><%= @medium.genre %></i><br />
  <p><%= @medium.description %></p><br />
  <p><%= @medium.address %></p><br />

  <% if @medium.latitude.present? && @medium.longitude.present? %>
    
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @medium.latitude %>, lng: <%= @medium.longitude %>;

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDLVu0vNtdok_EM0fi9K4x1PMNcZAD-fdk&callback=initMap">
    </script>

    <div id="map"></div>
  <% end %>
    
  <div class="float-right">
    <% if current_user && current_user == @medium.user %>
      <%= link_to 'Edit', edit_medium_path(@medium), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', medium_path(@medium), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %> 
    
  </div>
</div> 

<div class="col-10 offset-1">

  <h1 class="float-left">Random Thoughts</h1>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
    JournalIt!!!
  </button>
</div>



<div class="clear"></div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Random Thoughts</h4>
      </div>
      <%= simple_form_for @comment, url: medium_comments_path(@medium) do |f| %>
        <div class="modal-body">
          <%= f.input :description, label: "Journal Entry" %> 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "JournalIt!!!", class: 'btn btn-primary' %>
        </div>
      <% end %> 
    </div>
  </div>
</div>


<div class='row'>
  <% @medium.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <b><%= comment.rating %></b> -
          <%= comment.description %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
</div>